Main page layout.
htmlacademy-adaptive/1924739-pink-24 pull request #2
Opened 2021-11-28 18:57 UTC by ant-druha

2021-11-28 19:47 UTC, summertime-fms requested changes

2021-11-28 19:47 UTC, summertime-fms commented on source/index.html
> +<html class="page" lang="ru" xmlns="http://www.w3.org/1999/xhtml">
1. Класс на корневом элементе, как правило, не нужен. Знаю, что в демках его пихает академия, но подумай сам - у тебя в теге html только head и body. Ну будут они элементами от блока page - но нужно ли это? Давай уберем. И у body класс тоже можно убрать, думаю. 
2. xmlns тут тоже не нужен.

2021-11-28 19:47 UTC, summertime-fms commented on source/index.html
> +    <header class="page-header">
Можно просто header, чтобы потом писать меньше надо было.

2021-11-28 19:47 UTC, summertime-fms commented on source/index.html
> +          <svg class="page-header__logo-image logo__image" width="59" height="40" xmlns="http://www.w3.org/2000/svg">
Логотип - всегда контентное изображение через img. Даже если это выглядит как текст, даже если это свгшка. Потому что, во первых, лого-важная семантическая часть сайта, а svg не семантический тег. Во-вторых робото поисковиков обычно выхватывают img c логотипом и индексируют для своих поисковых систем (например, робот яндекса закинет эту картинку в яндекс картинки по запросу pink)

2021-11-28 19:47 UTC, summertime-fms commented on source/index.html
> +        <nav class="main-nav">
Да, можно выделить в отдельный блок но для позиционирования можно на всякий сделать зависимость от header(header__main-nav main-nav)

2021-11-28 19:47 UTC, summertime-fms commented on source/index.html
> +          <button class="main-nav__toggle" type="button"><span class="visually-hidden">Открыть меню.</span></button>
Давай спан на новую строчку чтобы читать код было полегче. А можно вообще добавить aria-label и спан не понадобится. А еще есть атрибут aria-pressed который дает знать слабовидящим в какой позиции находится твоя кнопка-тогл. Принимает значение true и false. Начальное положение, естественно, false

2021-11-28 19:47 UTC, summertime-fms commented on source/index.html
> +    <main class="page-main">
можно убрать, вряд ли пригодится

2021-11-28 19:47 UTC, summertime-fms commented on source/index.html
> +          <h2 class="intro__title">Взгляните на жизнь иначе!</h2>
Если все заголовки на странице имеют одинаковые  параметры, то можно стилизовать их по классу title. А осттупы предоставить intro__title, block__title, another-block__title and so on

2021-11-28 19:47 UTC, summertime-fms commented on source/index.html
> +          <div class="intro__image-front"></div>
Зачем? Для фонового изображения телефона? Лучше дать фон секции тогда, чтобы в разметке не было подохрительных пустых дивов. Да и в принципе можно контентным сделать, я думаю так как все таки главный экран сайта.

2021-11-28 19:47 UTC, summertime-fms commented on source/index.html
> +            <li class="intro__store-item"><a href="#" class="intro__store-link intro__store-link--apple"></a></li>
Ссылочки давай на новые строки, чтобы было более читабельно. Ну и по ТЗ они должны вести на маркетплейсы соответствующие. Давай добавим.

2021-11-28 19:47 UTC, summertime-fms commented on source/index.html
> +        <div class="info__wrapper">
Если ты добавил обертку чтобы потом делать сетку на флексах то ок. Но если делать на гридах то можно дропнуть эту оберкту.  Решай как тебе удобнее

2021-11-28 19:47 UTC, summertime-fms commented on source/index.html
> +            <h3 class="info__effect-title">Эффект на 24 часа!</h3>
Кажется, h2

2021-11-28 19:47 UTC, summertime-fms commented on source/index.html
> +            <button class="reviews__prev" type="button"><span class="visually-hidden">Предыдущий отзыв</span></button>
Либо спан на новую строчку либо aria-label

2021-11-28 19:47 UTC, summertime-fms commented on source/index.html
> +                  <span class="tariffs__feature-name">Розовый фильтр</span>
Можно без спана. Просто текст сразу в li

2021-11-28 19:47 UTC, summertime-fms commented on source/index.html
> +                  <span class="tariffs__feature-name">Розовый фильтр</span>
Всего нижележащего тоже касается.

2021-11-28 19:47 UTC, summertime-fms commented on source/index.html
> +            <p class="contacts__address-text">ул. Большая Конюшенная, 19/8</p>
Есть классный семантический тег address.

2021-11-28 19:47 UTC, summertime-fms commented on source/index.html
> +    <footer class="page-footer">
Можно просто footer

2021-11-28 19:47 UTC, summertime-fms commented on source/index.html
> +          <svg class="page-footer__logo-image logo__image" width="59" height="40" xmlns="http://www.w3.org/2000/svg">
Та же история. что и в шапке. Контентным надо сделать.

2021-11-28 19:47 UTC, summertime-fms commented on source/index.html
> +        <div class="page-footer__social social">
Можно не оборачивать в див ибо список он и так блочный)

2021-11-28 19:47 UTC, summertime-fms commented on source/index.html
> +            <li class="social__item"><a href="#" class="social__link social__link--twitter">Мы в Твиттере</a></li>
На новую строчку. А текста в макете нет. Текст скорее всего ты забыл обернуть в спан спрятанный. ну и опять же как вариант -  aria-label.

2021-11-28 19:47 UTC, summertime-fms commented on source/index.html
> +          <a class="copyright__link" href="https://htmlacademy.ru/intensive/adaptive">
А давай для удобства сделаем весь копирайт ссылкой, чтобы не надо было выцеливать только лого. Все оберни в ссылку. параграф не нужен. Текст + свгшка.

2021-11-28 19:54 UTC, ant-druha commented on source/index.html
> +          <svg class="page-header__logo-image logo__image" width="59" height="40" xmlns="http://www.w3.org/2000/svg">
Да, понимаю, что контентеое. Но как его тогда по hover стилизовать?

2021-11-28 19:56 UTC, ant-druha commented on source/index.html
> +          <svg class="page-footer__logo-image logo__image" width="59" height="40" xmlns="http://www.w3.org/2000/svg">
Тот же вопрос...:)

2021-11-30 16:47 UTC, ant-druha commented on source/index.html
> +          <svg class="page-header__logo-image logo__image" width="59" height="40" xmlns="http://www.w3.org/2000/svg">
С лого разобрались в общем, тк оно меняет цвет - оставляем в разметке.

2021-11-30 16:48 UTC, ant-druha commented on source/index.html
> +        <nav class="main-nav">
Спасибо, это я пропустил.

2021-11-30 16:52 UTC, ant-druha commented on source/index.html
> +          <button class="main-nav__toggle" type="button"><span class="visually-hidden">Открыть меню.</span></button>
>А можно вообще добавить aria-label и спан не понадобится.

В академии рекомендуют в [первую очердь](https://up.htmlacademy.ru/htmlcss/32/criteries#ALLY-02) добавлять в разметке, если не получается использовать аттрибуты. Думаешь, лучше атрибутом? Я если честно не знаю почему так. Может из-за того чтобы не было проблем в совместимости?

2021-11-30 17:05 UTC, ant-druha commented on source/index.html
> +          <div class="intro__image-front"></div>
Не был уверен как лучше сделать тк эта рука с телефоном на переднем плане отделена от фона на заднем плане и меняет положение с изменением ширины экрана. Через `img` норм будет?

2021-11-30 17:15 UTC, ant-druha commented on source/index.html
> +        <div class="info__wrapper">
Так далеко еще не думал:) Возможно гридами буду. Пока точно не могу сказать. Если буду градом - дропну. Спасибо.

2021-11-30 17:18 UTC, ant-druha commented on source/index.html
> +            <h3 class="info__effect-title">Эффект на 24 часа!</h3>
Это section внутри другого section, в котором уже есть h2. Я бы h3 поставил тут. Не согласен?

2021-11-30 17:20 UTC, ant-druha commented on source/index.html
> +                  <span class="tariffs__feature-name">Розовый фильтр</span>
Я тут предполагал как я буду двигать эти элементы и текст при изменении экрана, когда это превратится в таблицу. Подумал обернуть это в отдельный класс, чтобы ?возможно? гридом его изменить потом. Но не уверен как это лучше делать вообще. Попробовать через таблицу сразу заверстать, наверное.

2021-11-30 17:28 UTC, ant-druha commented on source/index.html
> +            <p class="contacts__address-text">ул. Большая Конюшенная, 19/8</p>
Почему-то посчитал что `address` внутри `p` не допускается.

2021-11-30 17:31 UTC, ant-druha commented on source/index.html
> +            <p class="contacts__address-text">ул. Большая Конюшенная, 19/8</p>
Почему-то валидатор ругается если использую `<p> <address></address></p>`, но ОК с разметкой, если не добавляю закрывающего `p`: `<p> <address></address>`. Не могу понять, почему.

2021-12-01 06:49 UTC, summertime-fms commented on source/index.html
> +          <svg class="header__logo-text logo__text" width="74" height="23" xmlns="http://www.w3.org/2000/svg">
А текст логотипа в шапке разве будет чем то отличаться от текста логотипа в другом месте? Первый класс лишний, мне кажется

2021-12-01 06:49 UTC, summertime-fms commented on source/index.html
> +            <li class="main-nav__item"><a class="main-nav__link">Главная</a></li>
С новой стоки ссылки

2021-12-01 06:49 UTC, summertime-fms commented on source/index.html
> +          <button class="main-nav__toggle" type="button"><span class="visually-hidden">Открыть меню.</span></button>
Да это долгая дискуссия, что предпочтительнее. Раньше академия вот и то и другое допускала, сейчас предпочтительнее спан. Разница небольшая на самом деле, скорее всего чисто визуальная. Мне, напрмер, удобно когда все в атрибутах и нет спанов, кому то наоборот. Можешь оставлять

2021-12-01 06:54 UTC, summertime-fms commented on source/index.html
> +            <h3 class="info__effect-title">Эффект на 24 часа!</h3>
![image](https://user-images.githubusercontent.com/59874681/144186073-e05971a6-75f7-499b-bf3c-ce988e4b75c3.png)

2021-12-01 06:54 UTC, summertime-fms commented on source/index.html
> +            <h3 class="info__effect-title">Эффект на 24 часа!</h3>
Лучше не надо секцию в секцию, это сбивает с толку. Там можно четко попилить сайт на блоке, каждый из которых section. И чтоб валидатор не ругался у каждого section должен быть h2. Поэтому давай тут избежим сложной логики. Используй див, например.

2021-12-01 06:54 UTC, summertime-fms commented on source/index.html
> +          <div class="intro__image-front"></div>
Да у тебя есть для заднего фона section а если еще что то понадобится фоном добавить то есть враппер. А еще есть множественные фоны в css) Так что пустой див - это последнее решение

2021-12-01 06:56 UTC, summertime-fms commented on source/index.html
> +              <a href="https://market.android.com/" class="intro__store-link intro__store-link--android"></a>
Забыли про доступность(

2021-12-01 06:56 UTC, summertime-fms commented on source/index.html
> +                  <span class="tariffs__feature-name">Розовый фильтр</span>
Ну списком мне кажется точно не вариант. Вернусь с этим скоро.

2021-12-01 06:57 UTC, summertime-fms commented on source/index.html
> +            <p class="contacts__address-text">ул. Большая Конюшенная, 19/8</p>
https://caninclude.glitch.me/can/include/?child=address&parent=p вот поэтому ругается) Не надо там ни дивов ни параграфов. Просто address. Можно же сделать его блочным через стили и управлять позиционированием.

2021-12-01 08:48 UTC, ant-druha commented on source/index.html
> +          <div class="intro__image-front"></div>
Сделал через `img`.

2021-12-01 09:21 UTC, ant-druha commented on source/index.html
> +                  <span class="tariffs__feature-name">Розовый фильтр</span>
Спасибо. Сделал таблицей, по твоей подсказке:)

2021-12-01 09:44 UTC, ant-druha commented on source/index.html
> +          <svg class="header__logo-text logo__text" width="74" height="23" xmlns="http://www.w3.org/2000/svg">
Убрал.

2021-12-01 09:57 UTC, merged